### ISSUE TITLE
Which volume is this referencing, consensus data or execution data or something else?

### ISSUE THREAD

**Issue by rueiwoqp** [eth-educators/eth-docker-docs#269]
https://github.com/eth-educators/eth-docker-docs/blob/c17a0a289e0454e26c7c3cee67e4cba58d0913fc/website/docs/Support/Moving.md?plain=1#L54

**Comment by yorickdowne** [comment]
Neither. This is for the validator client that holds the keys.

**Comment by rueiwoqp** [comment]
So, for example, which of these is the volume for the validator?
```
local     eth-staker_grafana-config
local     eth-staker_grafana-data
local     eth-staker_jwtsecret
local     eth-staker_loki-data
local     eth-staker_nm-eth1-data
local     eth-staker_prom-data
local     eth-staker_promtail-data
local     eth-staker_teku-data
```

**Comment by yorickdowne** [comment]
`eth-staker_teku-data` because you are using Teku, which doesn't distinguish.

I've changed the instructions to make this a lot easier.
