### ISSUE TITLE
Up command fails while old validator is still running

### ISSUE THREAD

**Issue by rueiwoqp** [eth-educators/eth-docker-docs#270]
https://github.com/eth-educators/eth-docker-docs/blob/fcdb931978805d1d01b897f6d6860f4b22b1b53f/website/docs/Support/SwitchClient.md?plain=1#L21

If you're switching clients and the old validator is still running and you try to execute `./ethd up` in the new validator directory, you will receive this error:

`Error response from daemon: driver failed programming external connectivity on endpoint eth-docker-consensus-1 Bind for 0.0.0.0:9000 failed: port is already allocated`

Maybe the docs should include instructions to execute `./ethd down` on the old validator.

**Comment by yorickdowne** [comment]
No need, you'd adjust ports. I assumed that to be self-evident - I'll make a note :)

**Comment by yorickdowne** [comment]
That entire section needed a rewrite. Take a look please, and see how it flows for you now.
