### ISSUE TITLE
misinformation about resyncing besu?

### ISSUE THREAD

**Issue by edwmurph** [eth-educators/eth-docker-docs#305]
[These docs](https://eth-docker.net/Usage/ResourceUsage/#disk-ram-cpu-requirements) suggest resyncing as a way to mitigate db growth

> YoY DB growth 2022->2023 was around 200 GiB. Resync should reduce Besu DB size when it has grown

but [this recent post](https://www.reddit.com/r/ethstaker/comments/12xnxxi/clearing_up_besubonsai_confusion_on_state_growth/) suggests that resyncing will only temporarily reduce the db size and negatively affects performance so it's not recommended

the quote i linked sent me down a misleading rabbit hole thinking i should be pruning besu's db. should the docs be updated to not spread misinformation about resyncing besu?

**Comment by yorickdowne** [comment]
I know that Reddit post. In my testing, "temporary" is months. For example, a recently (June) synced Besu of mine takes around 933 GiB, from about 850 GiB initially, where a Besu that's been running for a while may take 1.4 TiB or more. Fresh-synced size between 2022 and 2023 grew by only 200 GiB however.

The documentation is of necessity a snapshot in time. All clients change their behavior.

There is no pruning of Besu's DB. From my testing however, Besu does benefit from a resync when it runs out of space.
